name: Build macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Set environment variables
        run: |
          VERSION=$(cat src/main/resources/version.properties | grep "^version=" | cut -d= -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build dmg file
        run: ./gradlew packageDmg

      - name: Build debug jar
        run: ./gradlew packageUberJarForCurrentOS

      - name: Store dmg file
        uses: actions/upload-artifact@v2
        with:
          name: autokpass-compose-${{env.VERSION}}.dmg
          path: ./build/compose/binaries/main/dmg/autokpass-compose-${{env.VERSION}}.dmg

      - name: Store jar file
        uses: actions/upload-artifact@v2
        with:
          name: autokpass-compose-macos-x64-${{env.VERSION}}.jar
          path: ./build/compose/jars/autokpass-compose-macos-x64-${{env.VERSION}}.jar
