name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build debug jar
        run: ./gradlew packageUberJarForCurrentOS

      - name: Store jar file
        uses: actions/upload-artifact@v2
        with:
          name: autokpass-compose-linux-x64-1.0.0.jar
          path: ./build/compose/jars/autokpass-compose-linux-x64-1.0.0.jar
